name: rave_flutter
description: A new Flutter plugin for making payment with Flutterwave's rave.
version: 0.0.9-alpha+2
author: Wilberforce Uwadiegwu <faradaywilly@gmail.com>
homepage: https://github.com/wilburt/rave_flutter

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.20.2 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  http: ^0.13.3
  intl: ^0.17.0
  meta: ">=1.1.6 <2.0.0"
  async: ^2.6.1
  dio: ^4.0.0
  get_it: ^7.1.3
  equatable: ^2.0.2
  tripledes: ^2.1.0
  webview_flutter: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.flutterwave.rave_flutter
        pluginClass:  RaveFlutterPlugin
      ios:
        pluginClass:  RaveFlutterPlugin

  assets:
    - assets/images/
